"use client";
import Link from "next/link";
import { ArrowLeft, ExternalLink, FileCode, BookOpen } from "lucide-react";
import { Card, Button, Badge } from "@/components/ui";

const services = [
  { id: "auth", name: "auth-service", port: 8081, blurb: "Operator login, registration, JWT issuance" },
  { id: "carrier", name: "carrier-service", port: 8082, blurb: "CRUD for shipping carriers" },
  { id: "container", name: "container-service", port: 8083, blurb: "CRUD + status workflow for containers" },
  { id: "yard", name: "yard-service", port: 8084, blurb: "Yard slots and check-in/release workflow" },
  { id: "gate", name: "gate-service", port: 8085, blurb: "Truck check-in / check-out transactions" },
];

export default function DocsPage() {
  return (
    <main className="min-h-screen">
      <header className="border-b border-border">
        <div className="container flex h-14 items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="grid h-6 w-6 place-items-center rounded bg-foreground text-background font-mono text-xs font-bold">H</div>
            <span className="font-mono text-sm font-semibold">harborflow</span>
          </Link>
          <Button variant="ghost" size="sm" asChild><Link href="/dashboard">Dashboard <ArrowLeft className="h-3.5 w-3.5 rotate-180" /></Link></Button>
        </div>
      </header>
      <section className="border-b border-border">
        <div className="container py-12">
          <Badge variant="outline" className="mb-3"><BookOpen className="h-3 w-3" /> API reference</Badge>
          <h1 className="text-3xl font-semibold tracking-tight">Service API documentation</h1>
          <p className="mt-2 text-sm text-muted-foreground max-w-2xl">
            Each business service exposes its own OpenAPI spec at <code className="font-mono text-foreground">/v3/api-docs</code> and a Swagger UI at <code className="font-mono text-foreground">/swagger-ui.html</code>. Use the Authorize button with a Bearer JWT to call protected endpoints directly from the browser.
          </p>
        </div>
      </section>
      <section className="container py-10">
        <div className="space-y-3">
          {services.map((s) => (
            <Card key={s.id}>
              <div className="flex items-center justify-between px-5 py-4">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-sm font-semibold">{s.name}</span>
                    <span className="font-mono text-xs text-muted-foreground">:{s.port}</span>
                  </div>
                  <p className="text-xs text-muted-foreground mt-1">{s.blurb}</p>
                </div>
                <div className="flex items-center gap-2">
                  <Button asChild variant="outline" size="sm">
                    <a href={`http://localhost:${s.port}/swagger-ui.html`} target="_blank" rel="noopener noreferrer">Swagger UI <ExternalLink className="h-3 w-3" /></a>
                  </Button>
                  <Button asChild variant="ghost" size="sm">
                    <a href={`http://localhost:${s.port}/v3/api-docs`} target="_blank" rel="noopener noreferrer">OAS JSON <FileCode className="h-3 w-3" /></a>
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
        <div className="mt-10 rounded-lg border border-border bg-card p-5">
          <h3 className="text-sm font-semibold">Authorizing requests in Swagger</h3>
          <ol className="mt-3 space-y-2 text-sm text-muted-foreground list-decimal pl-5">
            <li>POST <code className="font-mono text-foreground">/api/auth/login</code> with <code className="font-mono text-foreground">{`{email,password}`}</code></li>
            <li>Copy the returned JWT from the response body</li>
            <li>Open any service's Swagger UI, click <strong>Authorize</strong>, paste the token</li>
            <li>All subsequent calls from Swagger UI carry the Bearer token — no JWT filter on those direct ports</li>
          </ol>
        </div>
        <div className="mt-6 text-[10px] font-mono text-muted-foreground flex items-center gap-2"><FileCode className="h-3 w-3" /> Specs generated by springdoc-openapi 2.5.0 · OpenAPI 3.0</div>
      </section>
    </main>
  );
}
